modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="tempz"
version="1.0.0"
displayName="TempZ"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="jacob, MCreator"

[[dependencies.tempz]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



